### ISSUE TITLE
Are these values right?

### ISSUE THREAD

**Issue by andychase** [k0nze/body_fat_calculator#1]
https://github.com/k0nze/body_fat_calculator/blob/902c28d015155396c44621e5e9f5b72684ccb4d8/index.html#L133

The values on page 501 are different then yours and the ones in the paper match ones found elsewhere

**Comment by andychase** [comment]
sorry "ik spreek geen Nederlands" as they say but I think you used the [third column](https://de.wikipedia.org/wiki/Calipometrie) here but that might refer to different collection sites then the jackson/polloc. You might want to double check

**Comment by k0nze** [comment]
It's been a while since I wrote this code. I will have a look into it over the coming days. 
PS: you don't need to speak Dutch the source is in German ;)

**Comment by k0nze** [comment]
I adjusted the values according to column 2 and 3 of https://de.wikipedia.org/wiki/Calipometrie
